package indicator

import (
	"math"
	"testing"
)

// TWO KINDS OF EVIDENCE, because either alone is weak.
//
// EXACT VALUES against a reference computed OUTSIDE Go, in Python, from the
// published definitions. That is what catches a convention error — Wilder's 1/n
// against 2/(n+1), a population against a sample deviation, a seed of xs[0]
// against the mean of the first n. Every one of those produces a series with the
// right shape and the right bounds, so no property test sees them.
//
// INVARIANTS that hold for ANY correct implementation. Those are what catch a
// shared misconception: if the Python and the Go were written from the same wrong
// idea, agreeing proves only that I made one mistake twice. RSI ∈ [0,100], SMA of
// a constant series is that constant, Bollinger bands straddle their middle —
// none of those depend on which convention is right.

// series is deterministic and generated by the same expression the Python
// reference used. No RNG: a fixture that differs per run cannot carry an exact
// expected value.
func series() []float64 {
	xs := []float64{100}
	for i := 1; i < 60; i++ {
		step := 3.0
		if i%3 == 0 {
			step = -5.0
		}
		xs = append(xs, round6(xs[len(xs)-1]+step+float64(i%7)*0.25))
	}
	return xs
}

func round6(f float64) float64 { return math.Round(f*1e6) / 1e6 }

func highs() []float64 {
	xs := series()
	out := make([]float64, len(xs))
	for i, c := range xs {
		out[i] = round6(c + 1.5 + float64(i%5)*0.1)
	}
	return out
}

func lows() []float64 {
	xs := series()
	out := make([]float64, len(xs))
	for i, c := range xs {
		out[i] = round6(c - 1.5 - float64(i%4)*0.1)
	}
	return out
}

func mustClose(t *testing.T, name string, got, want, tol float64) {
	t.Helper()
	if math.Abs(got-want) > tol {
		t.Errorf("%s = %.10f, want %.10f (±%g) — computed independently in Python from the "+
			"published definition", name, got, want, tol)
	}
}

// ===== EXACT VALUES, against the out-of-Go reference =====

func TestExactValuesMatchTheIndependentReference(t *testing.T) {
	xs := series()

	// The fixture itself must match, or every expectation below is measured
	// against a different series and the agreement means nothing.
	for i, want := range []float64{100, 103.25, 106.75, 102.5, 106.5, 110.75, 107.25, 110.25} {
		if xs[i] != want {
			t.Fatalf("fixture diverged at [%d]: %v, want %v — the Go and Python series must be "+
				"the same numbers or nothing below is a comparison", i, xs[i], want)
		}
	}
	if len(xs) != 60 {
		t.Fatalf("fixture length %d, want 60", len(xs))
	}

	v, ok := SMA(xs, 14)
	if !ok {
		t.Fatal("SMA(14) over 60 bars said insufficient history")
	}
	mustClose(t, "SMA(14)", v, 159.4821428571, 1e-9)

	v, _ = EMA(xs, 12)
	mustClose(t, "EMA(12)", v, 160.5765055100, 1e-9)
	v, _ = EMA(xs, 26)
	mustClose(t, "EMA(26)", v, 152.8851627633, 1e-9)

	// THE CONVENTION CHECK. With alpha=2/(n+1) instead of Wilder's 1/n this
	// returns ≈68.6 rather than 66.12 — same shape, same bounds, wrong number,
	// and no property test below can tell.
	v, _ = RSI(xs, 14)
	mustClose(t, "RSI(14) [Wilder 1/n]", v, 66.1199471337, 1e-9)

	m, ok := MACD(xs, 12, 26, 9)
	if !ok {
		t.Fatal("MACD(12,26,9) over 60 bars said insufficient history")
	}
	mustClose(t, "MACD", m.MACD, 7.6913427467, 1e-9)
	mustClose(t, "MACD signal", m.Signal, 7.6019494213, 1e-9)
	mustClose(t, "MACD histogram", m.Histogram, 0.0893933254, 1e-9)

	b, _ := Bollinger(xs, 20, 2)
	// POPULATION deviation. The sample one gives 6.7595 and bands at 169.71/142.67
	// — a 2.6% difference that never looks wrong.
	mustClose(t, "Bollinger middle", b.Middle, 156.1875, 1e-9)
	mustClose(t, "Bollinger upper", b.Upper, 169.3640653719, 1e-9)
	mustClose(t, "Bollinger lower", b.Lower, 143.0109346281, 1e-9)

	a, ok := ATR(highs(), lows(), xs, 14)
	if !ok {
		t.Fatal("ATR(14) said insufficient history")
	}
	mustClose(t, "ATR(14) [Wilder 1/n]", a, 5.5625971931, 1e-9)

	rv, _ := RealizedVol(xs, 20)
	mustClose(t, "RealizedVol(20)", rv, 0.0246639411, 1e-9)
}

// ===== INSUFFICIENT HISTORY IS ok=false, NEVER A NUMBER =====

// The failure this package exists to avoid. Zero is a valid RSI, 50 is a valid
// RSI, and NaN propagates until it surfaces somewhere unrelated — each makes "no
// answer" indistinguishable from a reading.
func TestInsufficientHistoryNeverReturnsANumber(t *testing.T) {
	short := series()[:9]

	cases := []struct {
		name string
		fn   func() (float64, bool)
	}{
		{"SMA(14)", func() (float64, bool) { return SMA(short, 14) }},
		{"EMA(14)", func() (float64, bool) { return EMA(short, 14) }},
		{"RSI(14)", func() (float64, bool) { return RSI(short, 14) }},
		{"RealizedVol(20)", func() (float64, bool) { return RealizedVol(short, 20) }},
		{"ATR(14)", func() (float64, bool) { return ATR(highs()[:9], lows()[:9], short, 14) }},
	}
	for _, c := range cases {
		v, ok := c.fn()
		if ok {
			t.Errorf("%s answered %v over %d bars — a 14-period indicator over 9 bars has no "+
				"value, and any number here is indistinguishable from a real reading", c.name, v, len(short))
		}
		if v != 0 {
			t.Errorf("%s returned %v alongside ok=false — the value must be the zero value so a "+
				"caller that ignores ok gets an obvious wrong answer rather than a plausible one",
				c.name, v)
		}
	}
	if _, ok := MACD(short, 12, 26, 9); ok {
		t.Error("MACD answered over 9 bars")
	}
	if _, ok := Bollinger(short, 20, 2); ok {
		t.Error("Bollinger answered over 9 bars")
	}
}

// RSI NEEDS n+1 PRICES, NOT n. The input is n changes, and a change needs two
// prices. An implementation that accepts n is off by one bar forever — invisible
// in the value, visible in every comparison to a chart.
func TestRSIRequiresOneMorePriceThanItsPeriod(t *testing.T) {
	xs := series()
	if _, ok := RSI(xs[:14], 14); ok {
		t.Error("RSI(14) answered over exactly 14 prices — that is only 13 changes")
	}
	if _, ok := RSI(xs[:15], 14); !ok {
		t.Error("RSI(14) refused 15 prices, which is exactly 14 changes")
	}
}

// ===== INVARIANTS: true for any correct implementation =====

// A CONSTANT SERIES. Every average is the constant, the deviation is zero, and
// the true range is zero. Convention-independent, and it catches a whole class of
// weighting and indexing errors at once.
func TestAConstantSeriesCollapsesEveryIndicator(t *testing.T) {
	const c = 42.5
	xs := make([]float64, 60)
	for i := range xs {
		xs[i] = c
	}

	if v, _ := SMA(xs, 14); math.Abs(v-c) > 1e-12 {
		t.Errorf("SMA of a constant = %v, want %v", v, c)
	}
	if v, _ := EMA(xs, 12); math.Abs(v-c) > 1e-12 {
		t.Errorf("EMA of a constant = %v, want %v — a seeding error shows up here", v, c)
	}
	b, _ := Bollinger(xs, 20, 2)
	if math.Abs(b.Upper-c) > 1e-12 || math.Abs(b.Lower-c) > 1e-12 {
		t.Errorf("Bollinger bands on a constant = [%v,%v], want both %v", b.Lower, b.Upper, c)
	}
	if v, _ := RealizedVol(xs, 20); v != 0 {
		t.Errorf("RealizedVol of a constant = %v, want 0", v)
	}
	// A flat series has no gains AND no losses. Wilder's avgLoss is zero, which
	// this defines as 100 — an unmoved market is not oversold.
	if v, ok := RSI(xs, 14); !ok || v != 100 {
		t.Errorf("RSI of a constant = %v (ok=%v), want 100 by the zero-loss definition", v, ok)
	}
}

// A MONOTONICALLY RISING SERIES HAS RSI 100, and a falling one has RSI 0. The two
// endpoints of the definition, and they catch a swapped gain/loss — which is
// otherwise a sign error that keeps the value in range and inverts every signal
// built on it.
func TestRSIEndpoints(t *testing.T) {
	up := make([]float64, 40)
	down := make([]float64, 40)
	for i := range up {
		up[i] = 100 + float64(i)
		down[i] = 100 - float64(i)
	}
	if v, ok := RSI(up, 14); !ok || v != 100 {
		t.Errorf("RSI of a monotonically rising series = %v (ok=%v), want 100", v, ok)
	}
	if v, ok := RSI(down, 14); !ok || v > 1e-9 {
		t.Errorf("RSI of a monotonically falling series = %v (ok=%v), want 0 — a value near 100 "+
			"here is gains and losses swapped, which keeps RSI in range and inverts every rule "+
			"built on it", v, ok)
	}
}

// RSI STAYS IN [0,100] EVERYWHERE on the fixture, at several periods. The bound
// is the definition; a value outside it is not a mis-tuned indicator but a broken
// one.
func TestRSIStaysWithinItsPublishedBounds(t *testing.T) {
	xs := series()
	for _, n := range []int{2, 5, 14, 21} {
		for i := n + 1; i <= len(xs); i++ {
			v, ok := RSI(xs[:i], n)
			if !ok {
				t.Fatalf("RSI(%d) refused %d prices", n, i)
			}
			if v < 0 || v > 100 {
				t.Fatalf("RSI(%d) at bar %d = %v, outside [0,100]", n, i, v)
			}
		}
	}
}

// AN AVERAGE LIES BETWEEN THE MIN AND MAX OF WHAT IT AVERAGES. Catches a runaway
// recursion or a weight that does not sum to one — both of which can otherwise
// track the price closely enough to look right.
func TestMovingAveragesStayInsideTheirWindow(t *testing.T) {
	xs := series()
	lo, hi := xs[0], xs[0]
	for _, x := range xs {
		lo, hi = math.Min(lo, x), math.Max(hi, x)
	}
	for _, n := range []int{5, 12, 26} {
		if v, _ := SMA(xs, n); v < lo || v > hi {
			t.Errorf("SMA(%d) = %v, outside [%v,%v]", n, v, lo, hi)
		}
		if v, _ := EMA(xs, n); v < lo || v > hi {
			t.Errorf("EMA(%d) = %v, outside [%v,%v]", n, v, lo, hi)
		}
	}
}

// BOLLINGER BANDS STRADDLE THEIR MIDDLE, AND THE MIDDLE IS THE SMA.
func TestBollingerStraddlesItsMiddle(t *testing.T) {
	xs := series()
	b, _ := Bollinger(xs, 20, 2)
	sma, _ := SMA(xs, 20)
	if math.Abs(b.Middle-sma) > 1e-12 {
		t.Errorf("Bollinger middle %v is not SMA(20) %v", b.Middle, sma)
	}
	if !(b.Lower < b.Middle && b.Middle < b.Upper) {
		t.Errorf("bands do not straddle: %v < %v < %v", b.Lower, b.Middle, b.Upper)
	}
	// Width is normalised, so it is comparable across instruments. The raw span
	// is not.
	if math.Abs(b.Width-(b.Upper-b.Lower)/b.Middle) > 1e-12 {
		t.Errorf("Width %v is not (upper-lower)/middle", b.Width)
	}
	// A WIDER k IS A WIDER BAND, monotonically.
	b3, _ := Bollinger(xs, 20, 3)
	if !(b3.Upper > b.Upper && b3.Lower < b.Lower) {
		t.Error("3 deviations did not produce a wider band than 2")
	}
}

// ATR IS NON-NEGATIVE AND AT LEAST THE MEAN HIGH−LOW WOULD BE.
//
// True range includes the two gap terms, so it can only be larger than the plain
// range — never smaller. An implementation that dropped them would fail this the
// moment a bar gaps.
func TestATRIsNonNegativeAndGapAware(t *testing.T) {
	hi, lo, cl := highs(), lows(), series()
	a, ok := ATR(hi, lo, cl, 14)
	if !ok || a < 0 {
		t.Fatalf("ATR = %v (ok=%v)", a, ok)
	}

	// A DELIBERATE GAP: move one bar far above the previous close without
	// widening its own high−low. Only the gap terms can see it.
	hi2 := append([]float64(nil), hi...)
	lo2 := append([]float64(nil), lo...)
	cl2 := append([]float64(nil), cl...)
	i := len(cl2) - 2
	hi2[i] += 50
	lo2[i] += 50
	cl2[i] += 50
	gapped, _ := ATR(hi2, lo2, cl2, 14)
	if gapped <= a {
		t.Errorf("ATR did not rise on a gapped bar (%v vs %v) — the |high−prevClose| terms are "+
			"missing, and the one time they matter is a venue halt, exactly when a risk-sizing "+
			"input must not understate", gapped, a)
	}
}

// A NON-POSITIVE PRICE HAS NO LOG RETURN, and inventing one would put a
// fabricated number into a sizing input.
func TestRealizedVolRefusesNonPositivePrices(t *testing.T) {
	xs := series()
	xs[len(xs)-3] = 0
	if v, ok := RealizedVol(xs, 20); ok {
		t.Errorf("RealizedVol answered %v over a series containing a zero price", v)
	}
}

// MACD's HISTOGRAM IS ITS OWN DIFFERENCE — an identity, so it cannot drift from
// the two lines it is derived from.
func TestMACDHistogramIsItsOwnDifference(t *testing.T) {
	m, ok := MACD(series(), 12, 26, 9)
	if !ok {
		t.Fatal("MACD refused a 60-bar series")
	}
	if math.Abs(m.Histogram-(m.MACD-m.Signal)) > 1e-12 {
		t.Errorf("histogram %v != MACD %v − signal %v", m.Histogram, m.MACD, m.Signal)
	}
	// FAST MUST BE FASTER THAN SLOW. Reversed, the sign of every reading flips
	// while the magnitudes stay identical — so it is refused rather than computed.
	if _, ok := MACD(series(), 26, 12, 9); ok {
		t.Error("MACD accepted fast >= slow, which silently inverts every reading")
	}
}

// EMA CONSUMES THE WHOLE SERIES, NOT THE LAST n.
//
// A caller that slices first gets something that is neither an EMA nor an SMA, so
// this pins that a longer history changes the answer — the property that makes it
// exponential.
func TestEMADependsOnHistoryBeyondItsPeriod(t *testing.T) {
	xs := series()
	full, _ := EMA(xs, 12)
	sliced, _ := EMA(xs[len(xs)-12:], 12)
	if math.Abs(full-sliced) < 1e-9 {
		t.Error("EMA over the full series equals EMA over just the last 12 — it is behaving " +
			"like an SMA, which means the recursion is not running")
	}
	// And the SMA of that same window is the SLICED value, by definition: an EMA
	// seeded with the mean of the first n and given nothing further IS that mean.
	sma, _ := SMA(xs, 12)
	if math.Abs(sliced-sma) > 1e-12 {
		t.Errorf("EMA of exactly n values = %v, want the SMA %v — that is what the seed is", sliced, sma)
	}
}
