// Package ledger is the event-sourced investment book-of-record (IBOR-01b): it
// folds OMS-01 fills and cash movements into a point-in-time book of positions
// and cash. The journal of LedgerEntry events is the source of truth; the Book is
// their fold, so the same journal always replays to the same book (and the same
// NAV) — the PERS-01 snapshot/replay stance applied to accounting state.
//
// # Double entry
//
// Every entry carries a signed position leg (quantity at price) and/or a signed
// cash leg. A trade is both: a BUY adds the position and removes cash; a cash
// movement is a pure cash leg. The book never invents the cash side — the caller
// (the fill adapter, a corporate-action processor) computes it, so the fold is a
// faithful double-entry accumulator.
//
// # Bitemporal
//
// Each entry has an effective time (when it economically happened) and a
// knowledge time (when the book learned of it). ReplayAsOf reconstructs the book
// as it was known at a (effective, knowledge) point, so a late-arriving entry
// restates history without destroying what was previously reported — the
// knowledge-time correctness IBOR-01c requires.
package ledger

import (
	"math/big"
	"sort"
	"strconv"
	"time"

	"github.com/eighred/kanz/internal/costbasis"
)

// EntryType classifies a journal entry by what produced it (mirrors
// accounting.v1.EntryType).
type EntryType int

const (
	EntryUnspecified EntryType = iota
	EntryTrade
	EntryCash
	EntryFee
	EntryCorporateAction
	EntryAccrual

	// entryTypeCount is the iota sentinel that makes the enumeration below
	// COUNTABLE. Adding a type above it bumps this value, and
	// TestEntryTypesCoversEveryDeclaredType fails until EntryTypes and
	// entryTypeNames are extended too. Keep it LAST.
	entryTypeCount
)

// EntryTypes is every entry type the book can fold, in declaration order.
//
// IT EXISTS SO A CONSUMER CAN ENUMERATE THEM RATHER THAN HAND-LISTING THEM
// (#588). The accounting composition root seeds one metric series per entry type
// to say which of them anything actually PRODUCES; a hand-written list there
// would mean a new entry type shipped with no series at all — absent rather than
// zero — until its first posting, which is precisely the invisibility that
// posture is built to remove. Derived from this slice, a new type is seeded at 0
// on the first scrape after it is declared.
//
// The slice is written out rather than generated by a loop over entryTypeCount
// so that adding a type is a compile-visible edit HERE; the count check is what
// stops it from being forgotten.
var EntryTypes = []EntryType{
	EntryUnspecified,
	EntryTrade,
	EntryCash,
	EntryFee,
	EntryCorporateAction,
	EntryAccrual,
}

// entryTypeNames are the stable wire/label names for each type. They are metric
// LABEL VALUES and a PromQL alert may name them, so they are frozen: renaming one
// silently breaks every query that used it. "corporate_action" is spelled the way
// nav.go's attribution component already spells it.
var entryTypeNames = [...]string{
	EntryUnspecified:     "unspecified",
	EntryTrade:           "trade",
	EntryCash:            "cash",
	EntryFee:             "fee",
	EntryCorporateAction: "corporate_action",
	EntryAccrual:         "accrual",
}

// String is the stable name of the entry type. An undeclared value renders as
// entry_type(N) rather than panicking or rendering as empty: a metric label that
// came out blank would be indistinguishable from an unset one.
func (t EntryType) String() string {
	if t < 0 || int(t) >= len(entryTypeNames) {
		return "entry_type(" + strconv.Itoa(int(t)) + ")"
	}
	return entryTypeNames[t]
}

// Event is one immutable journal entry — the internal working shape behind
// accounting.v1.LedgerEntry. Money and quantity are exact (*big.Rat); the journal
// is append-only, so a correction is a new offsetting Event, never a mutation.
type Event struct {
	EntryID     string
	PortfolioID string
	// VenueAccountID is the EXCHANGE ACCOUNT whose collateral this entry moved.
	//
	// The ledger has always kept cash per PORTFOLIO. An exchange does not: it margins
	// and LIQUIDATES per ACCOUNT. If two portfolios settle into one account, a
	// per-portfolio ledger reports cash that a liquidation in the other portfolio has
	// already consumed — books that are not imprecise but WRONG, in the direction that
	// loses money. So an entry records the account it settled against, and the engine
	// refuses to write it into an account the transaction did not declare.
	//
	// Set from the Fill (the account that actually executed), and from a CASH
	// MOVEMENT that settled against an exchange account (#415) — funding okx-sub-1,
	// or paying a fee out of it. Empty for an entry that genuinely touches none: an
	// investor subscription into the fund's own bank, a corporate action.
	//
	// EMPTY IS A CLAIM, NOT AN ABSENCE — migration 0003 makes '' the positive
	// declaration that no exchange account was touched, so leaving it unset on a
	// movement that DID reach one writes a falsehood rather than omitting a detail.
	VenueAccountID string
	Type           EntryType
	InstrumentID   string

	// Quantity is the signed position change; Price the per-unit price. Both nil
	// for a pure cash entry.
	Quantity *big.Rat
	Price    *big.Rat

	// Cash is the signed cash leg (+ increases cash) in CashCurrency. Nil ⇒ no
	// cash effect.
	Cash         *big.Rat
	CashCurrency string

	// Action carries corporate-action parameters for an EntryCorporateAction
	// entry. Its effects (split scaling, dividend/coupon cash, merger conversion)
	// are evaluated against the POSITION-AT-EFFECTIVE-TIME during the fold, not
	// precomputed — so a restatement that changes the holding at the ex-date
	// changes the action's cash/position effect too (knowledge-time correctness).
	Action *Action

	// Effective is the domain time the event happened; Knowledge is when the book
	// learned of it. A later Knowledge with an earlier Effective is a restatement.
	Effective time.Time
	Knowledge time.Time

	// SettlementBasis is whether these legs have actually changed hands, and
	// SettlementDate is when they do (or did). THE THIRD TEMPORAL AXIS, and it is
	// not the bitemporal one (#1043): Effective/Knowledge is one event seen twice
	// over time, this is one uncontested event with two economic dates.
	//
	// THE ZERO VALUE IS SettlementUnknown AND THAT IS THE WHOLE DESIGN. A producer
	// that cannot assert a settlement basis leaves it unset, and an unset basis
	// keeps the entry OUT of the settled book rather than into it — see
	// SettlementBasis, and Book.SettlementBasisComplete for the fail-closed read.
	// SettlementDate is likewise zero when nobody asserted one; it is not defaulted
	// to Effective, because "settles the day it traded" is a claim about a venue's
	// convention and must be made by whoever knows it, in one place (FromFill).
	SettlementBasis SettlementBasis
	SettlementDate  time.Time

	SourceRef string
}

// CorpActKind is the kind of corporate action an Action describes.
type CorpActKind int

const (
	CorpActUnspecified CorpActKind = iota
	CorpActSplit
	CorpActDividend
	CorpActMerger
	CorpActCoupon
)

// Action is the parameters of a corporate action, applied at fold time against
// the affected position. The package corpact builds these from a CorporateAction.
type Action struct {
	Kind CorpActKind

	// Ratio is the share-conversion factor for a SPLIT (2.0 = 2:1) or a MERGER
	// exchange (target shares per source share).
	Ratio *big.Rat

	// PerUnit is the cash factor per unit held: dividend-per-share (DIVIDEND),
	// coupon cash per unit of face (COUPON), or cash-per-share (MERGER).
	PerUnit *big.Rat

	// Target is the instrument received in a MERGER.
	Target string

	// Currency stamps any cash leg the action produces.
	Currency string
}

// Position is the running state of one holding: signed quantity, the
// non-negative average cost of the open lot, and cumulative realized P&L.
// An ALIAS to the platform's lot, not a copy of it (#428). The IBOR's holding and
// the OMS's holding were separate structs folded by separate copies of one
// calculation; the exported name stays because callers use ledger.Position.
type Position = costbasis.Lot

func newPosition() *Position { return costbasis.NewLot() }

// Book is the folded state of one portfolio: positions by instrument, cash by
// currency, and accrued income by currency (earned-not-received, carried in NAV).
// It is the fold of the journal — replayable and snapshot-restorable.
//
// # Two bases, one journal (#1043)
//
// Positions/Cash are the TRADED basis: everything the portfolio has traded,
// settled or not. SettledPositions/SettledCash are the SETTLED basis: only the
// legs that have actually changed hands. THEY ARE THE SAME ENTRIES FOLDED TWICE,
// not a second store — a caller asks for the basis its question needs instead of
// choosing between two books that can drift. A pre-trade buying-power gate wants
// settled cash; a mandate exposure limit wants traded positions; NAV wants both
// and the difference between them is the unsettled receivable.
//
// The settled fold is only as good as what the producers assert, so a caller that
// reads it MUST check SettlementBasisComplete first. See SettlementBasis.
type Book struct {
	PortfolioID string
	Positions   map[string]*Position
	Cash        map[string]*big.Rat
	Accrued     map[string]*big.Rat

	// SettledPositions and SettledCash are the settled-basis fold of the same
	// journal: an entry contributes to them only when it asserts
	// SettlementSettled.
	//
	// ACCRUED HAS NO SETTLED TWIN, on purpose. Accrued income is earned-not-
	// received by definition, so a "settled accrual" is a contradiction; folding
	// it into a settled balance would assert cash the fund has not been paid,
	// which is the exact direction this axis exists to stop.
	SettledPositions map[string]*Position
	SettledCash      map[string]*big.Rat

	// settlementStated is whether this book's settled fold covers every entry
	// behind it. NewBook starts true (an empty book states an empty settled view
	// correctly) and RestoreBook clears it for a checkpoint written before the
	// settlement axis existed, whose settled maps are empty because nobody wrote
	// them rather than because nothing settled.
	settlementStated bool
	// unknownSettlement and pendingSettlement count the folded entries that did
	// not assert a basis, and those that asserted a future one. They are what
	// makes a zero settled balance readable: "nothing has settled" and "nine
	// entries never said" are different answers and must not look the same.
	unknownSettlement int
	pendingSettlement int

	seen map[string]bool
	// maxEffective is the latest effective_time this book has folded. It is the
	// fence a snapshot carries into Snapshot.MaxEffective: the fold is
	// order-sensitive (weighted-average cost realizes P&L in sequence), so
	// resuming from a checkpoint is only equal to a full replay while every
	// entry appended afterwards is effective at or after everything already in
	// it. See MaterializeCurrent, which refuses the checkpoint otherwise.
	maxEffective time.Time
}

// NewBook returns an empty book for a portfolio.
func NewBook(portfolioID string) *Book {
	return &Book{
		PortfolioID:      portfolioID,
		Positions:        make(map[string]*Position),
		Cash:             make(map[string]*big.Rat),
		Accrued:          make(map[string]*big.Rat),
		SettledPositions: make(map[string]*Position),
		SettledCash:      make(map[string]*big.Rat),
		// An empty book has folded nothing, so its empty settled view is a
		// complete and correct statement rather than an unwritten one.
		settlementStated: true,
		seen:             make(map[string]bool),
	}
}

// basisFold is one basis's half of the book — the positions and cash map an
// entry is folded into. It exists so the corporate-action and weighted-average
// folds are written ONCE and run over whichever basis an entry belongs to
// (#1043). A second copy of foldCorpAct for the settled maps is the shape #428
// already paid for here: three copies of one calculation had drifted, and the
// repair was one implementation, not three careful ones.
type basisFold struct {
	positions map[string]*Position
	cash      map[string]*big.Rat
}

// traded is the fold every entry contributes to: what the portfolio has traded.
func (b *Book) traded() basisFold { return basisFold{b.Positions, b.Cash} }

// settled is the fold only an entry asserting SettlementSettled contributes to:
// what has actually changed hands.
func (b *Book) settled() basisFold { return basisFold{b.SettledPositions, b.SettledCash} }

// Apply folds one entry into the book. It is idempotent on EntryID — a replay or
// redelivery of the same entry is a no-op, so the book is exactly-once over the
// at-least-once journal. An entry for another portfolio is ignored.
func (b *Book) Apply(e *Event) {
	if e == nil || e.EntryID == "" || (e.PortfolioID != "" && e.PortfolioID != b.PortfolioID) {
		return
	}
	if b.seen[e.EntryID] {
		return
	}
	b.seen[e.EntryID] = true
	if e.Effective.After(b.maxEffective) {
		b.maxEffective = e.Effective
	}

	// THE BASIS IS COUNTED BEFORE ANY LEG IS LOOKED AT, and before the
	// corporate-action return below. An entry that asserts nothing is a gap in
	// the settled view whether or not it happened to carry a quantity, and
	// counting it only on the paths that move something would report a book as
	// complete because the entry it could not classify was empty.
	settles := e.SettlementBasis == SettlementSettled
	switch e.SettlementBasis {
	case SettlementSettled:
	case SettlementPending:
		b.pendingSettlement++
	default:
		b.unknownSettlement++
	}

	if e.Type == EntryCorporateAction && e.Action != nil {
		b.traded().foldCorpAct(e.InstrumentID, e.Action)
		if settles {
			b.settled().foldCorpAct(e.InstrumentID, e.Action)
		}
		return
	}

	if e.InstrumentID != "" && e.Quantity != nil && e.Quantity.Sign() != 0 {
		b.traded().foldPosition(e.InstrumentID, e.Quantity, orZero(e.Price))
		if settles {
			b.settled().foldPosition(e.InstrumentID, e.Quantity, orZero(e.Price))
		}
	}
	if e.Cash != nil && e.Cash.Sign() != 0 {
		ccy := e.CashCurrency
		if e.Type == EntryAccrual {
			// No settled twin — see Book.SettledPositions on why accrued income
			// has no settled balance.
			add(b.Accrued, ccy, e.Cash)
		} else {
			add(b.Cash, ccy, e.Cash)
			if settles {
				add(b.SettledCash, ccy, e.Cash)
			}
		}
	}
}

// SettlementBasisComplete reports whether this book can answer a settled-basis
// question at all.
//
// FALSE MEANS FAIL CLOSED, NOT "PROBABLY FINE". It is false when any folded
// entry asserted no settlement basis, and when the book was restored from a
// checkpoint written before the settlement axis existed. In either case the
// settled maps are a LOWER BOUND of unknown tightness, and a control that spends
// against them — a pre-trade buying-power gate above all — would be authorising
// money on a number nobody computed. A critical unknown refuses; it does not
// collapse to zero and proceed.
func (b *Book) SettlementBasisComplete() bool {
	return b.settlementStated && b.unknownSettlement == 0
}

// UnknownSettlementEntries is how many folded entries asserted no settlement
// basis — the reason SettlementBasisComplete is false when it is, and the number
// that separates "nothing has settled" from "nobody said".
func (b *Book) UnknownSettlementEntries() int { return b.unknownSettlement }

// PendingSettlementEntries is how many folded entries are traded-but-not-settled.
// Distinct from the unknown count: pending is an ANSWER, unknown is the absence
// of one.
func (b *Book) PendingSettlementEntries() int { return b.pendingSettlement }

// foldCorpAct applies a corporate action against the position in instrument as it
// stands at this point in the fold. Splits scale the lot (conserving market
// value); dividends/coupons pay cash on the held quantity; a merger converts the
// holding into the target instrument, carrying the cost basis and paying any cash.
func (f basisFold) foldCorpAct(instrument string, a *Action) {
	l := f.positions[instrument]
	if l == nil || l.Qty.Sign() == 0 {
		return // nothing held at the ex-date: the action has no effect
	}
	switch a.Kind {
	case CorpActSplit:
		if a.Ratio == nil || a.Ratio.Sign() <= 0 {
			return
		}
		// qty × ratio, avg ÷ ratio → market value (qty × price) is conserved when
		// the price also divides by ratio.
		l.Qty = new(big.Rat).Mul(l.Qty, a.Ratio)
		l.AvgCost = new(big.Rat).Quo(l.AvgCost, a.Ratio)

	case CorpActDividend, CorpActCoupon:
		if a.PerUnit == nil {
			return
		}
		// Cash on the held quantity (absolute: a long receives, a short pays).
		cash := new(big.Rat).Mul(l.Qty, a.PerUnit)
		add(f.cash, a.Currency, cash)

	case CorpActMerger:
		if a.Target == "" || a.Ratio == nil {
			return
		}
		q := new(big.Rat).Set(l.Qty)
		basis := new(big.Rat).Mul(new(big.Rat).Abs(q), l.AvgCost) // cost carried over
		// Source position closes with no realized P&L — the basis transfers.
		l.Qty = new(big.Rat)
		l.AvgCost = new(big.Rat)
		newQty := new(big.Rat).Mul(q, a.Ratio)
		f.foldContribution(a.Target, newQty, basis)
		if a.PerUnit != nil && a.PerUnit.Sign() != 0 {
			add(f.cash, a.Currency, new(big.Rat).Mul(q, a.PerUnit))
		}
	}
}

// foldContribution adds a quantity carrying a given total cost basis into a
// holding, weighted-averaging with any existing lot. Used by a merger to open the
// target position at the source's carried basis (avg = totalCost / |qty|).
func (f basisFold) foldContribution(instrument string, qty, totalCost *big.Rat) {
	if qty.Sign() == 0 {
		return
	}
	avg := new(big.Rat).Quo(new(big.Rat).Abs(totalCost), new(big.Rat).Abs(qty))
	f.foldPosition(instrument, qty, avg)
}

// foldPosition applies a signed quantity at price using the PLATFORM'S
// weighted-average-cost fold, booking realized P&L on the closed portion.
//
// THE ARITHMETIC IS NO LONGER HERE, and that is the repair (#428). This used to be
// a hand-copy of the OMS position projector's fold, and said so:
//
//	"Two copies of one calculation is the standing risk; the next edit to either
//	 should not have to rediscover which one had the guard."
//
// There were three copies, not two, and they had drifted — tv-sync's netted fees
// into realized P&L while this one and the OMS's did not. internal/costbasis is
// the one implementation; the IBOR and the OMS book now agree by construction
// rather than by inspection.
func (f basisFold) foldPosition(instrument string, signed, price *big.Rat) {
	l := f.positions[instrument]
	if l == nil {
		l = newPosition()
		f.positions[instrument] = l
	}
	costbasis.Fold(l, signed, price)
}

// CashBalance returns the cash held in a currency (zero if none).
func (b *Book) CashBalance(currency string) *big.Rat {
	if v := b.Cash[currency]; v != nil {
		return new(big.Rat).Set(v)
	}
	return new(big.Rat)
}

// AccruedBalance returns the accrued income in a currency (zero if none).
func (b *Book) AccruedBalance(currency string) *big.Rat {
	if v := b.Accrued[currency]; v != nil {
		return new(big.Rat).Set(v)
	}
	return new(big.Rat)
}

// Replay folds a journal into a fresh book in (effective, knowledge) order — the
// canonical reconstruction. Replaying the same journal yields the same book.
func Replay(portfolioID string, events []*Event) *Book {
	b := NewBook(portfolioID)
	for _, e := range sortedFor(events, time.Time{}, time.Time{}, false) {
		b.Apply(e)
	}
	return b
}

// ReplayAsOf reconstructs the book as it was known at knowledgeAsOf for economic
// effects up to effectiveAsOf — the bitemporal point-in-time read. A zero time on
// either axis means "no bound on that axis". This is what makes a restatement
// knowledge-time correct: a read as-of an early knowledge time never sees an entry
// the book had not yet learned of.
func ReplayAsOf(portfolioID string, events []*Event, effectiveAsOf, knowledgeAsOf time.Time) *Book {
	b := NewBook(portfolioID)
	for _, e := range sortedFor(events, effectiveAsOf, knowledgeAsOf, true) {
		b.Apply(e)
	}
	return b
}

// sortedFor returns the events, optionally filtered to those at or before the
// effective/knowledge bounds, in deterministic fold order (effective, then
// knowledge, then entry id).
func sortedFor(events []*Event, effBound, knowBound time.Time, filter bool) []*Event {
	out := make([]*Event, 0, len(events))
	for _, e := range events {
		if filter {
			if !effBound.IsZero() && e.Effective.After(effBound) {
				continue
			}
			if !knowBound.IsZero() && e.Knowledge.After(knowBound) {
				continue
			}
		}
		out = append(out, e)
	}
	sort.SliceStable(out, func(i, j int) bool {
		if !out[i].Effective.Equal(out[j].Effective) {
			return out[i].Effective.Before(out[j].Effective)
		}
		if !out[i].Knowledge.Equal(out[j].Knowledge) {
			return out[i].Knowledge.Before(out[j].Knowledge)
		}
		return out[i].EntryID < out[j].EntryID
	})
	return out
}

func add(m map[string]*big.Rat, key string, v *big.Rat) {
	cur := m[key]
	if cur == nil {
		cur = new(big.Rat)
		m[key] = cur
	}
	cur.Add(cur, v)
}

func orZero(r *big.Rat) *big.Rat {
	if r == nil {
		return new(big.Rat)
	}
	return r
}
