apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream-install.yaml
  - network-policy.yaml
  - pdb.yaml

images:
  - name: ghcr.io/cloudnative-pg/cloudnative-pg
    newName: ghcr.io/cloudnative-pg/cloudnative-pg
    digest: sha256:a2701eb97cdd2a34b1fdb2cb51987f544b706e40bec72ae7146cd8580efefebb

patches:
  - target:
      kind: Deployment
      name: cnpg-controller-manager
    path: deployment-patch.yaml
