apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-oms-query
  namespace: kanz-services
  labels:
    app.kubernetes.io/part-of: kanz
spec:
  podSelector:
    matchLabels:
      app: oms
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - { protocol: TCP, port: 9090 }
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kanz-observability
      ports:
        - { protocol: TCP, port: 8090 }
