apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-oms-query
  namespace: kanz-services
  labels:
    app.kubernetes.io/part-of: kanz
spec:
  podSelector:
    matchLabels:
      app: oms
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - { protocol: TCP, port: 9090 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-oms-query-egress-from-gateway
  namespace: kanz-services
  labels:
    app.kubernetes.io/part-of: kanz
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: oms
      ports:
        - { protocol: TCP, port: 9090 }
