// Package tenantgen renders a tenant's compute manifests from the shared bases
// under infra/deploy. WHICH services a tenant gets, and why each one is needed,
// is declared once in services.go.
//
// MT-02 (corrected design): a tenant's compute manifest is COMMITTED, PLAIN
// YAML at infra/deploy/tenants/<tenant>/<service>-<tenant>.yaml, picked up by the
// ApplicationSet's existing "workloads" component (directory.recurse: true
// over infra/deploy) — no kustomize, no ArgoCD flag, no out-of-repo
// prerequisite. What is in git is exactly what deploys.
//
// A committed COPY of the base drifts the moment the base changes and
// nothing compares the two — this repo's signature defect. What makes a
// committed copy safe here is that it is never hand-edited: Render is the
// ONE generator, called by cmd/kanz-tenantgen (which provision-tenant.sh's
// `compute` step invokes) and by test/arch/tenant_compute_test.go, which
// re-renders every committed tenant manifest from the LIVE base on every CI
// run and fails the build on any byte difference. That guard only works if
// Render is deterministic: same base bytes + same tenant id must ALWAYS
// produce byte-identical output, or the guard flaps independent of any real
// drift. See the determinism note on Render below.
package tenantgen

import (
	"bytes"
	"fmt"
	"io"
	"regexp"

	"gopkg.in/yaml.v3"
)

// tenantIDRE matches a DNS-safe tenant id: lowercase alphanumeric with
// internal hyphens only — the same shape tenantctl.sh, provision-tenant.sh,
// and infra/nats/tenancy.yaml's account names already assume.
var tenantIDRE = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`)

// generatedHeader is written at the top of every rendered manifest so a
// reader of the committed file knows it is not hand-maintained and where to
// regenerate it from. Its only variable is the base path, which comes from
// the declared Service, so it does not threaten determinism.
func generatedHeader(base string) string {
	return "" +
		"# Code generated by internal/tenantgen (cmd/kanz-tenantgen). DO NOT EDIT BY HAND.\n" +
		"#\n" +
		"# Rendered from " + base + " for one tenant (MT-02). CI\n" +
		"# (test/arch/tenant_compute_test.go) re-renders this file from the live base\n" +
		"# on every run and fails the build on any byte difference. If the base\n" +
		"# changed underneath this file, regenerate it — do not hand-patch:\n" +
		"#   go run ./cmd/kanz-tenantgen -tenant <tenant>\n"
}

// Render deterministically renders svc's base manifest (ServiceAccount,
// Service, Deployment, PodDisruptionBudget) for one tenant.
//
// DETERMINISM CONTRACT: Render(base, svc, tenant) called twice with the same
// arguments MUST produce byte-identical output. This holds because (a) YAML
// documents are decoded into map[string]interface{} and gopkg.in/yaml.v3
// sorts map keys before encoding (encode.go, sort.Sort(keyList(...))), so
// key order never depends on map iteration order, and (b) nothing here reads
// the clock, the environment, or any other ambient state. Do not introduce
// either without re-establishing this contract — the drift guard in
// test/arch/tenant_compute_test.go depends on it exactly as much as
// correctness does.
//
// Every object the base declares is renamed <name>-<tenant>, and every
// selector the per-tenant isolation boundary depends on is stamped with
// tenant: <tenant>: the Service's spec.selector, the Deployment's
// spec.selector.matchLabels + pod-template labels +
// topologySpreadConstraints label selector, and the PodDisruptionBudget's
// spec.selector.matchLabels. Without this, every tenant's pods carry the
// identical `app: <service>` label in the shared kanz-services namespace, and
// tenant A's Service/PDB would see tenant B's pods too. metadata.labels is
// stamped on every object, not just selectors.
//
// The Deployment's serviceAccountName is rewritten to the renamed
// ServiceAccount, and svc.TenantEnv (on the container named svc.Container)
// is set to tenant.
//
// On that same container, svc.DropEnv removes the __system__-only dependencies a
// tenant must not inherit, and svc.SetEnv overrides the controls whose correct
// default differs between the platform and a tenant — today, the mandate
// requirement (#779). Both are held to the same dead-entry rule: an entry that
// matches nothing fails the render rather than passing silently, and so does an
// override the base already makes.
func Render(base []byte, svc Service, tenant string) ([]byte, error) {
	if err := validateTenant(tenant); err != nil {
		return nil, err
	}
	if svc.Name == "" || svc.Base == "" || svc.Container == "" || svc.TenantEnv == "" {
		return nil, fmt.Errorf("tenantgen: incomplete service descriptor %+v — every field is load-bearing; "+
			"a rendered deployment with no tenant env var still serves __system__ while wearing the tenant's name", svc)
	}
	if err := validateEnvRules(svc); err != nil {
		return nil, err
	}

	dec := yaml.NewDecoder(bytes.NewReader(base))
	var rendered [][]byte
	for {
		var doc map[string]interface{}
		err := dec.Decode(&doc)
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("tenantgen: decode base document %d: %w", len(rendered)+1, err)
		}
		if doc == nil {
			continue
		}
		if err := transform(doc, svc, tenant); err != nil {
			return nil, fmt.Errorf("tenantgen: document %d: %w", len(rendered)+1, err)
		}
		b, err := marshalDoc(doc)
		if err != nil {
			return nil, fmt.Errorf("tenantgen: marshal document %d: %w", len(rendered)+1, err)
		}
		rendered = append(rendered, b)
	}
	if len(rendered) == 0 {
		return nil, fmt.Errorf("tenantgen: base has no YAML documents")
	}

	var out bytes.Buffer
	out.WriteString(generatedHeader(svc.Base))
	for _, b := range rendered {
		out.WriteString("---\n")
		out.Write(b)
	}
	return out.Bytes(), nil
}

// marshalDoc encodes doc with a fixed 2-space indent, matching the style
// used elsewhere in infra/deploy.
func marshalDoc(doc map[string]interface{}) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// transform mutates doc in place. It knows exactly the four kinds the declared
// bases use. An unrecognized kind is a hard error rather than
// a silent pass-through: skipping an object's selectors would render a
// tenant manifest that LOOKS isolated but is not, which is the exact defect
// this generator exists to close. Adding a new kind to the base means
// teaching transform about its selectors first.
func transform(doc map[string]interface{}, svc Service, tenant string) error {
	kind, _ := doc["kind"].(string)
	metadata, ok := doc["metadata"].(map[string]interface{})
	if !ok {
		return fmt.Errorf("no metadata map (kind=%q)", kind)
	}
	name, ok := metadata["name"].(string)
	if !ok || name == "" {
		return fmt.Errorf("no metadata.name (kind=%q)", kind)
	}
	metadata["name"] = WorkloadName(name, tenant)
	stampTenant(ensureMap(metadata, "labels"), tenant)

	spec, _ := doc["spec"].(map[string]interface{})

	switch kind {
	case "ServiceAccount":
		// Name + top-level labels only — handled above.

	case "Service":
		if spec == nil {
			return fmt.Errorf("Service %q has no spec", name)
		}
		stampTenant(ensureMap(spec, "selector"), tenant)

	case "PodDisruptionBudget":
		if spec == nil {
			return fmt.Errorf("PodDisruptionBudget %q has no spec", name)
		}
		selector := ensureMap(spec, "selector")
		stampTenant(ensureMap(selector, "matchLabels"), tenant)

	case "Deployment":
		if err := transformDeployment(spec, svc, name, tenant); err != nil {
			return err
		}

	case "Rollout":
		// AN ARGO ROLLOUT IS A DEPLOYMENT FOR EVERY FIELD THIS RENDERS. Its
		// spec.selector, spec.template and the pod spec beneath are the same
		// shapes, so the same transform runs — a second near-copy of it would be
		// the drift this package's own DropEnv/naming rules exist to prevent.
		//
		// WHAT IT MUST NOT TOUCH is the canary analysis. spec.strategy.canary
		// references an AnalysisTemplate BY NAME (templateName:
		// risk-engine-canary), and that template is NOT rendered per tenant: it
		// is a shared statement of what a healthy canary looks like, and it takes
		// the rollouts-pod-template-hash as an argument so its queries already
		// scope to one rollout's canary pods. Renaming the reference here would
		// point every tenant's rollout at an AnalysisTemplate that does not
		// exist, and Argo treats a missing template as an analysis FAILURE —
		// which aborts the rollout. A tenant's risk engine would be undeployable,
		// and the symptom would be a rollback rather than a not-found.
		//
		// THE EXEMPTION THIS RETIRES CLAIMED OTHERWISE. It said "the analysis
		// template selects on `app: risk-engine`, which every tenant's rollout
		// would share". It does not: infra/deploy/analysis-template.yaml contains
		// ZERO app selectors — every query filters on
		// rollouts_pod_template_hash="{{args.canary-hash}}", which Argo sets
		// per Rollout revision. Two tenants' rollouts cannot collide through it.
		if err := transformDeployment(spec, svc, name, tenant); err != nil {
			return err
		}

	case "ScaledObject":
		if spec == nil {
			return fmt.Errorf("ScaledObject %q has no spec", name)
		}
		// THE SCALE TARGET IS THE ONE FIELD THAT MATTERS, and getting it wrong is
		// not a rendering bug — it is one tenant's autoscaler driving another
		// tenant's workload. metadata.name is suffixed above like everything
		// else; if scaleTargetRef.name were left pointing at "risk-engine", the
		// tenant's ScaledObject would scale the PLATFORM rollout from the
		// tenant's own queue depth, and KEDA would report it healthy while doing
		// it.
		ref, ok := spec["scaleTargetRef"].(map[string]interface{})
		if !ok {
			return fmt.Errorf("ScaledObject %q has no spec.scaleTargetRef", name)
		}
		target, ok := ref["name"].(string)
		if !ok || target == "" {
			return fmt.Errorf("ScaledObject %q has no spec.scaleTargetRef.name", name)
		}
		ref["name"] = WorkloadName(target, tenant)

	default:
		return fmt.Errorf("unrecognized kind %q — teach transform() its selectors before this generator can render it", kind)
	}

	return nil
}

func transformDeployment(spec map[string]interface{}, svc Service, name, tenant string) error {
	if spec == nil {
		return fmt.Errorf("Deployment %q has no spec", name)
	}
	selector := ensureMap(spec, "selector")
	stampTenant(ensureMap(selector, "matchLabels"), tenant)

	tmpl := ensureMap(spec, "template")
	tmplMeta := ensureMap(tmpl, "metadata")
	stampTenant(ensureMap(tmplMeta, "labels"), tenant)

	tmplSpec := ensureMap(tmpl, "spec")

	sa, _ := tmplSpec["serviceAccountName"].(string)
	if sa == "" {
		return fmt.Errorf("Deployment %q template has no serviceAccountName", name)
	}
	tmplSpec["serviceAccountName"] = WorkloadName(sa, tenant)

	if spreads, ok := tmplSpec["topologySpreadConstraints"].([]interface{}); ok {
		for _, s := range spreads {
			sm, ok := s.(map[string]interface{})
			if !ok {
				continue
			}
			ls := ensureMap(sm, "labelSelector")
			stampTenant(ensureMap(ls, "matchLabels"), tenant)
		}
	}

	containers, _ := tmplSpec["containers"].([]interface{})
	patchedEnv := false
	for _, c := range containers {
		cm, ok := c.(map[string]interface{})
		if !ok {
			continue
		}
		if cname, _ := cm["name"].(string); cname != svc.Container {
			continue
		}
		drop := make(map[string]string, len(svc.DropEnv))
		for _, d := range svc.DropEnv {
			drop[d.Name] = d.Why
		}
		set := make(map[string]SetEnvVar, len(svc.SetEnv))
		for _, o := range svc.SetEnv {
			set[o.Name] = o
		}
		env, _ := cm["env"].([]interface{})
		kept := make([]interface{}, 0, len(env))
		dropped := map[string]bool{}
		overridden := map[string]bool{}
		for _, e := range env {
			em, ok := e.(map[string]interface{})
			if !ok {
				kept = append(kept, e)
				continue
			}
			en, _ := em["name"].(string)
			if _, remove := drop[en]; remove {
				dropped[en] = true
				continue
			}
			if o, override := set[en]; override {
				// A CONTROL SUPPLIED BY REFERENCE CANNOT BE OVERRIDDEN WITH A LITERAL.
				// An env entry carrying both value and valueFrom is rejected by the API
				// server, so the render would produce a manifest that fails to APPLY
				// rather than to render — a tenant whose workload never starts,
				// discovered at deploy time rather than here.
				if _, fromRef := em["valueFrom"]; fromRef {
					return fmt.Errorf("Deployment %q: SetEnv names %s, which the base supplies from a "+
						"valueFrom reference. Overriding it with a literal would produce an env entry "+
						"carrying both value and valueFrom, which the API server rejects — and the "+
						"rendered manifest would fail to apply rather than to render (%s)",
						name, o.Name, o.Why)
				}
				// A VALUE THE BASE ALREADY SETS IS AN ERROR, not a no-op. The entry
				// exists to record a posture the tenant runs and the platform does
				// not; once the base agrees, the override enforces nothing while its
				// Why goes on reading as a live decision. Deleting it is the honest
				// outcome — the same dead-exemption rule DropEnv is held to.
				if base, has := em["value"]; has && fmt.Sprintf("%v", base) == o.Value {
					return fmt.Errorf("Deployment %q: SetEnv sets %s=%q, which the base ALREADY sets. "+
						"An override that changes nothing records a reason for a difference that has "+
						"stopped existing; delete the entry rather than keep it as a no-op (%s)",
						name, o.Name, o.Value, o.Why)
				}
				em["value"] = o.Value
				overridden[en] = true
				kept = append(kept, e)
				continue
			}
			if en == svc.TenantEnv {
				em["value"] = tenant
				patchedEnv = true
			}
			kept = append(kept, e)
		}
		// A DECLARED DROP THAT MATCHED NOTHING IS AN ERROR. The base having
		// renamed or removed the variable is exactly when this entry stops
		// protecting anything, and a silent no-op would leave the reason recorded
		// in services.go while the behaviour it describes had quietly ended — the
		// dead-exemption failure mode the arch guards are built to refuse.
		for _, d := range svc.DropEnv {
			if !dropped[d.Name] {
				return fmt.Errorf("Deployment %q: DropEnv names %s, which container %q does not "+
					"set. Either the base renamed it — in which case update the entry — or the "+
					"variable is gone and the entry must be deleted; a drop that matches nothing "+
					"records a reason for behaviour that has stopped happening (%s)",
					name, d.Name, svc.Container, d.Why)
			}
		}
		// A DECLARED OVERRIDE THAT MATCHED NOTHING IS AN ERROR, for the reason the
		// drop check above states: the base having renamed or removed the variable
		// is exactly when this entry stops arming anything, and the tenant would
		// silently fall back to whatever the base does — which for a *_REQUIRE_*
		// control is the permissive posture (#779).
		for _, o := range svc.SetEnv {
			if !overridden[o.Name] {
				return fmt.Errorf("Deployment %q: SetEnv names %s, which container %q does not "+
					"set. Either the base renamed it — in which case update the entry — or the "+
					"variable is gone and the entry must be deleted; an override that matches "+
					"nothing leaves this tenant on the base's default (%s)",
					name, o.Name, svc.Container, o.Why)
			}
		}
		cm["env"] = kept
	}
	if !patchedEnv {
		return fmt.Errorf("Deployment %q: no %s env var found on a container named %q", name, svc.TenantEnv, svc.Container)
	}
	return nil
}

// validateEnvRules rejects a service descriptor whose DropEnv and SetEnv
// contradict each other or the tenant pin, before any document is touched.
//
// These are declaration errors, not rendering ones: a variable cannot be both
// removed and given a value, and the tenant pin is RENDERED (to the tenant id)
// rather than configured — an override naming it would either fight the pin or
// silently win, and a per-tenant deployment reading the wrong tenant is the one
// defect this package exists to close.
func validateEnvRules(svc Service) error {
	drop := map[string]bool{}
	for _, d := range svc.DropEnv {
		drop[d.Name] = true
	}
	seen := map[string]bool{}
	for _, o := range svc.SetEnv {
		if o.Name == "" || o.Value == "" || o.Why == "" {
			return fmt.Errorf("tenantgen: service %q: SetEnv entry %+v is incomplete — a name, a value "+
				"and the reason the tenant's posture differs are all required", svc.Name, o)
		}
		if seen[o.Name] {
			return fmt.Errorf("tenantgen: service %q: SetEnv names %s twice; which value renders would "+
				"depend on declaration order", svc.Name, o.Name)
		}
		seen[o.Name] = true
		if drop[o.Name] {
			return fmt.Errorf("tenantgen: service %q: %s is in both DropEnv and SetEnv — a variable "+
				"cannot be both removed from the render and given a value in it", svc.Name, o.Name)
		}
		if o.Name == svc.TenantEnv {
			return fmt.Errorf("tenantgen: service %q: SetEnv names the tenant pin %s, which Render "+
				"sets to the tenant id; an override here would decide which tenant this deployment "+
				"serves", svc.Name, o.Name)
		}
	}
	return nil
}

// ensureMap returns m[key] as a map[string]interface{}, creating and
// installing an empty one if absent, so a base that has not yet declared
// (e.g.) metadata.labels still gets one stamped rather than panicking on a
// nil map write.
func ensureMap(m map[string]interface{}, key string) map[string]interface{} {
	if v, ok := m[key].(map[string]interface{}); ok {
		return v
	}
	nm := map[string]interface{}{}
	m[key] = nm
	return nm
}

// stampTenant sets tenant: <tenant> on a labels/selector map. It never
// removes or overwrites any other key — only ever adds this one.
func stampTenant(m map[string]interface{}, tenant string) {
	m["tenant"] = tenant
}

// ServiceAccountName extracts the metadata.name of the ServiceAccount
// document within a rendered manifest (or any multi-document k8s YAML). It
// is used by test/arch/tenant_compute_test.go to derive the SPIFFE ID a
// rendered manifest actually produces, rather than assuming a naming
// convention the generator might one day change.
func ServiceAccountName(rendered []byte) (string, error) {
	dec := yaml.NewDecoder(bytes.NewReader(rendered))
	for {
		var doc struct {
			Kind     string `yaml:"kind"`
			Metadata struct {
				Name string `yaml:"name"`
			} `yaml:"metadata"`
		}
		err := dec.Decode(&doc)
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", fmt.Errorf("decode rendered manifest: %w", err)
		}
		if doc.Kind == "ServiceAccount" {
			if doc.Metadata.Name == "" {
				return "", fmt.Errorf("rendered ServiceAccount has empty metadata.name")
			}
			return doc.Metadata.Name, nil
		}
	}
	return "", fmt.Errorf("rendered manifest has no ServiceAccount document")
}
