// Package tenantgen renders a tenant's compute manifests from the shared bases
// under infra/deploy. WHICH services a tenant gets, and why each one is needed,
// is declared once in services.go.
//
// MT-02 (corrected design): a tenant's compute manifest is COMMITTED, PLAIN
// YAML at infra/deploy/tenants/<tenant>/<service>-<tenant>.yaml, picked up by the
// ApplicationSet's existing "workloads" component (directory.recurse: true
// over infra/deploy) — no kustomize, no ArgoCD flag, no out-of-repo
// prerequisite. What is in git is exactly what deploys.
//
// A committed COPY of the base drifts the moment the base changes and
// nothing compares the two — this repo's signature defect. What makes a
// committed copy safe here is that it is never hand-edited: Render is the
// ONE generator, called by cmd/kanz-tenantgen (which provision-tenant.sh's
// `compute` step invokes) and by test/arch/tenant_compute_test.go, which
// re-renders every committed tenant manifest from the LIVE base on every CI
// run and fails the build on any byte difference. That guard only works if
// Render is deterministic: same base bytes + same tenant id must ALWAYS
// produce byte-identical output, or the guard flaps independent of any real
// drift. See the determinism note on Render below.
package tenantgen

import (
	"bytes"
	"fmt"
	"io"
	"regexp"

	"gopkg.in/yaml.v3"
)

// tenantIDRE matches a DNS-safe tenant id: lowercase alphanumeric with
// internal hyphens only — the same shape tenantctl.sh, provision-tenant.sh,
// and infra/nats/tenancy.yaml's account names already assume.
var tenantIDRE = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`)

// generatedHeader is written at the top of every rendered manifest so a
// reader of the committed file knows it is not hand-maintained and where to
// regenerate it from. Its only variable is the base path, which comes from
// the declared Service, so it does not threaten determinism.
func generatedHeader(base string) string {
	return "" +
		"# Code generated by internal/tenantgen (cmd/kanz-tenantgen). DO NOT EDIT BY HAND.\n" +
		"#\n" +
		"# Rendered from " + base + " for one tenant (MT-02). CI\n" +
		"# (test/arch/tenant_compute_test.go) re-renders this file from the live base\n" +
		"# on every run and fails the build on any byte difference. If the base\n" +
		"# changed underneath this file, regenerate it — do not hand-patch:\n" +
		"#   go run ./cmd/kanz-tenantgen -tenant <tenant>\n"
}

// Render deterministically renders svc's base manifest (ServiceAccount,
// Service, Deployment, PodDisruptionBudget) for one tenant.
//
// DETERMINISM CONTRACT: Render(base, svc, tenant) called twice with the same
// arguments MUST produce byte-identical output. This holds because (a) YAML
// documents are decoded into map[string]interface{} and gopkg.in/yaml.v3
// sorts map keys before encoding (encode.go, sort.Sort(keyList(...))), so
// key order never depends on map iteration order, and (b) nothing here reads
// the clock, the environment, or any other ambient state. Do not introduce
// either without re-establishing this contract — the drift guard in
// test/arch/tenant_compute_test.go depends on it exactly as much as
// correctness does.
//
// Every object the base declares is renamed <name>-<tenant>, and every
// selector the per-tenant isolation boundary depends on is stamped with
// tenant: <tenant>: the Service's spec.selector, the Deployment's
// spec.selector.matchLabels + pod-template labels +
// topologySpreadConstraints label selector, and the PodDisruptionBudget's
// spec.selector.matchLabels. Without this, every tenant's pods carry the
// identical `app: <service>` label in the shared kanz-services namespace, and
// tenant A's Service/PDB would see tenant B's pods too. metadata.labels is
// stamped on every object, not just selectors.
//
// The Deployment's serviceAccountName is rewritten to the renamed
// ServiceAccount, and svc.TenantEnv (on the container named svc.Container)
// is set to tenant.
func Render(base []byte, svc Service, tenant string) ([]byte, error) {
	if err := validateTenant(tenant); err != nil {
		return nil, err
	}
	if svc.Name == "" || svc.Base == "" || svc.Container == "" || svc.TenantEnv == "" {
		return nil, fmt.Errorf("tenantgen: incomplete service descriptor %+v — every field is load-bearing; "+
			"a rendered deployment with no tenant env var still serves __system__ while wearing the tenant's name", svc)
	}

	dec := yaml.NewDecoder(bytes.NewReader(base))
	var rendered [][]byte
	for {
		var doc map[string]interface{}
		err := dec.Decode(&doc)
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("tenantgen: decode base document %d: %w", len(rendered)+1, err)
		}
		if doc == nil {
			continue
		}
		if err := transform(doc, svc, tenant); err != nil {
			return nil, fmt.Errorf("tenantgen: document %d: %w", len(rendered)+1, err)
		}
		b, err := marshalDoc(doc)
		if err != nil {
			return nil, fmt.Errorf("tenantgen: marshal document %d: %w", len(rendered)+1, err)
		}
		rendered = append(rendered, b)
	}
	if len(rendered) == 0 {
		return nil, fmt.Errorf("tenantgen: base has no YAML documents")
	}

	var out bytes.Buffer
	out.WriteString(generatedHeader(svc.Base))
	for _, b := range rendered {
		out.WriteString("---\n")
		out.Write(b)
	}
	return out.Bytes(), nil
}

// marshalDoc encodes doc with a fixed 2-space indent, matching the style
// used elsewhere in infra/deploy.
func marshalDoc(doc map[string]interface{}) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// transform mutates doc in place. It knows exactly the four kinds the declared
// bases use. An unrecognized kind is a hard error rather than
// a silent pass-through: skipping an object's selectors would render a
// tenant manifest that LOOKS isolated but is not, which is the exact defect
// this generator exists to close. Adding a new kind to the base means
// teaching transform about its selectors first.
func transform(doc map[string]interface{}, svc Service, tenant string) error {
	kind, _ := doc["kind"].(string)
	metadata, ok := doc["metadata"].(map[string]interface{})
	if !ok {
		return fmt.Errorf("no metadata map (kind=%q)", kind)
	}
	name, ok := metadata["name"].(string)
	if !ok || name == "" {
		return fmt.Errorf("no metadata.name (kind=%q)", kind)
	}
	metadata["name"] = WorkloadName(name, tenant)
	stampTenant(ensureMap(metadata, "labels"), tenant)

	spec, _ := doc["spec"].(map[string]interface{})

	switch kind {
	case "ServiceAccount":
		// Name + top-level labels only — handled above.

	case "Service":
		if spec == nil {
			return fmt.Errorf("Service %q has no spec", name)
		}
		stampTenant(ensureMap(spec, "selector"), tenant)

	case "PodDisruptionBudget":
		if spec == nil {
			return fmt.Errorf("PodDisruptionBudget %q has no spec", name)
		}
		selector := ensureMap(spec, "selector")
		stampTenant(ensureMap(selector, "matchLabels"), tenant)

	case "Deployment":
		if err := transformDeployment(spec, svc, name, tenant); err != nil {
			return err
		}

	default:
		return fmt.Errorf("unrecognized kind %q — teach transform() its selectors before this generator can render it", kind)
	}

	return nil
}

func transformDeployment(spec map[string]interface{}, svc Service, name, tenant string) error {
	if spec == nil {
		return fmt.Errorf("Deployment %q has no spec", name)
	}
	selector := ensureMap(spec, "selector")
	stampTenant(ensureMap(selector, "matchLabels"), tenant)

	tmpl := ensureMap(spec, "template")
	tmplMeta := ensureMap(tmpl, "metadata")
	stampTenant(ensureMap(tmplMeta, "labels"), tenant)

	tmplSpec := ensureMap(tmpl, "spec")

	sa, _ := tmplSpec["serviceAccountName"].(string)
	if sa == "" {
		return fmt.Errorf("Deployment %q template has no serviceAccountName", name)
	}
	tmplSpec["serviceAccountName"] = WorkloadName(sa, tenant)

	if spreads, ok := tmplSpec["topologySpreadConstraints"].([]interface{}); ok {
		for _, s := range spreads {
			sm, ok := s.(map[string]interface{})
			if !ok {
				continue
			}
			ls := ensureMap(sm, "labelSelector")
			stampTenant(ensureMap(ls, "matchLabels"), tenant)
		}
	}

	containers, _ := tmplSpec["containers"].([]interface{})
	patchedEnv := false
	for _, c := range containers {
		cm, ok := c.(map[string]interface{})
		if !ok {
			continue
		}
		if cname, _ := cm["name"].(string); cname != svc.Container {
			continue
		}
		drop := make(map[string]string, len(svc.DropEnv))
		for _, d := range svc.DropEnv {
			drop[d.Name] = d.Why
		}
		env, _ := cm["env"].([]interface{})
		kept := make([]interface{}, 0, len(env))
		dropped := map[string]bool{}
		for _, e := range env {
			em, ok := e.(map[string]interface{})
			if !ok {
				kept = append(kept, e)
				continue
			}
			en, _ := em["name"].(string)
			if _, remove := drop[en]; remove {
				dropped[en] = true
				continue
			}
			if en == svc.TenantEnv {
				em["value"] = tenant
				patchedEnv = true
			}
			kept = append(kept, e)
		}
		// A DECLARED DROP THAT MATCHED NOTHING IS AN ERROR. The base having
		// renamed or removed the variable is exactly when this entry stops
		// protecting anything, and a silent no-op would leave the reason recorded
		// in services.go while the behaviour it describes had quietly ended — the
		// dead-exemption failure mode the arch guards are built to refuse.
		for _, d := range svc.DropEnv {
			if !dropped[d.Name] {
				return fmt.Errorf("Deployment %q: DropEnv names %s, which container %q does not "+
					"set. Either the base renamed it — in which case update the entry — or the "+
					"variable is gone and the entry must be deleted; a drop that matches nothing "+
					"records a reason for behaviour that has stopped happening (%s)",
					name, d.Name, svc.Container, d.Why)
			}
		}
		cm["env"] = kept
	}
	if !patchedEnv {
		return fmt.Errorf("Deployment %q: no %s env var found on a container named %q", name, svc.TenantEnv, svc.Container)
	}
	return nil
}

// ensureMap returns m[key] as a map[string]interface{}, creating and
// installing an empty one if absent, so a base that has not yet declared
// (e.g.) metadata.labels still gets one stamped rather than panicking on a
// nil map write.
func ensureMap(m map[string]interface{}, key string) map[string]interface{} {
	if v, ok := m[key].(map[string]interface{}); ok {
		return v
	}
	nm := map[string]interface{}{}
	m[key] = nm
	return nm
}

// stampTenant sets tenant: <tenant> on a labels/selector map. It never
// removes or overwrites any other key — only ever adds this one.
func stampTenant(m map[string]interface{}, tenant string) {
	m["tenant"] = tenant
}

// ServiceAccountName extracts the metadata.name of the ServiceAccount
// document within a rendered manifest (or any multi-document k8s YAML). It
// is used by test/arch/tenant_compute_test.go to derive the SPIFFE ID a
// rendered manifest actually produces, rather than assuming a naming
// convention the generator might one day change.
func ServiceAccountName(rendered []byte) (string, error) {
	dec := yaml.NewDecoder(bytes.NewReader(rendered))
	for {
		var doc struct {
			Kind     string `yaml:"kind"`
			Metadata struct {
				Name string `yaml:"name"`
			} `yaml:"metadata"`
		}
		err := dec.Decode(&doc)
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", fmt.Errorf("decode rendered manifest: %w", err)
		}
		if doc.Kind == "ServiceAccount" {
			if doc.Metadata.Name == "" {
				return "", fmt.Errorf("rendered ServiceAccount has empty metadata.name")
			}
			return doc.Metadata.Name, nil
		}
	}
	return "", fmt.Errorf("rendered manifest has no ServiceAccount document")
}
